### ISSUE TITLE
Need to add patch to older scylla version for scylladb/python-driver#233

### ISSUE THREAD

**Issue by fruch** [scylladb/python-driver-matrix#62]
https://github.com/scylladb/python-driver/pull/233

this cause of change took place in CCM, and we need to align the test, otherwise cleanup of sni_proxy docker image
isn't working correctly, and test keep hitting the wrong one.

**Comment by roydahan** [comment]
@temichus FYI

**Comment by fruch** [comment]
was done by @k0machi already
